baseurl = "https://blog.tjones.dev"
languageCode = "en"
title = "/home/tjones"
theme = "hucore"
copyright = "&copy; 2020 Tyler Jones"

pygmentsStyle = "perldoc"
pygmentsUseClasses = false

[taxonomies]
tag = "tags"
category = "categories"

[params]
description = "Your description here"
keywords = ["keyword 1", "keyword 2", "keyword 3"]
author = "Tyler Jones"
sharingicons = true

[permalinks]
post = ":filename"

[[params.social]]
url = "https://github.com/tjones879"
fa_icon = "fa-github"

[[params.social]]
url = "https://www.linkedin.com/in/tdjones879/"
fa_icon = "fa-linkedin-square"

[[params.social]]
url = "mailto:blog@tjones.dev"
fa_icon = "fa-envelope"
